force-app/main/default/objects/APEX_Candidate__c/APEX_Candidate__c.object-meta.xml
<CustomObject>
    <description>This object contain candidate detail</description>
    <label>Candidate</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Candidate Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/APEX_Candidate__c/fields/Age__c.field-meta.xml
<CustomField>
    <fullName>Age__c</fullName>
    <formula>YEAR( TODAY()  )- YEAR(Date_of_Birth__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Age</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/APEX_Candidate__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>This is Email field</description>
    <inlineHelpText>Insert valid email only</inlineHelpText>
    <label>Email</label>
    <required>true</required>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/APEX_Candidate__c/fields/Full_Name__c.field-meta.xml
<CustomField>
    <fullName>Full_Name__c</fullName>
    <formula>TEXT(Salutation__c)  &amp;  First_Name__c &amp;  Last_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Full Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/APEX_Candidate__c/fields/Jobs__c.field-meta.xml
<CustomField>
    <fullName>Jobs__c</fullName>
    <description>It should be able to relate a candidate to a job</description>
    <label>Job</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Candidates</relationshipLabel>
    <relationshipName>Candidates</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <description>This is a job object</description>
    <label>Job</label>
    <nameField>
        <displayFormat>J-{0000}</displayFormat>
        <label>Job Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <description>This is auto field</description>
    <displayFormat>JOB-{000}</displayFormat>
    <label>Name</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/classes/getByJobName.cls
public class getByJobName {
    
    public ApexPages.StandardSetController setCon {
        get {
            if(setCon == null) {
                setCon = new ApexPages.StandardSetController(Database.getQueryLocator(
                    [
                    
                    

			SELECT Name__c ,(SELECT id,Email__c , Full_Name__c from Candidates__r)
       		 from Job__c where id ='a065g000009HE38'

                    ]
                ));
            }
            return setCon;
        }
        set;
    }
    // Initialize setCon and return a list of records
    public List<Job__c> getOpportunities() {
        return (List<Job__c>) setCon.getRecords();
    }

    
    
    
    
    
    
   /*
    public List<Job__c> jobobj{get;set;}	
    
    
	
    public List<String> fields{get;set;}
    
    public getByJobName()
    {
        String jobName = 'JOB-006';
        records = [SELECT Name__c ,(SELECT Age__c , Full_Name__c from Candidates__r)
        from Job__c where Name__c =:jobName];
        
         fields = new List<String>{'Age__c','Full_Name__c'};
    }
  
    public static List<Job__c> searchByJObName()
    {
        String jobName = 'JOB-005';

		List<Job__c>  jobobj = [SELECT Name__c ,(SELECT Age__c , Full_Name__c from Candidates__r)
        from Job__c where Name__c =:jobName];
        
        return jobobj;
    }

*/

}