force-app/main/default/objects/APEX_Candidate__c/APEX_Candidate__c.object-meta.xml
<CustomObject>
    <description>This object contain candidate detail</description>
    <label>Candidate</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Candidate Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/APEX_Candidate__c/fields/Age__c.field-meta.xml
<CustomField>
    <fullName>Age__c</fullName>
    <formula>YEAR( TODAY()  )- YEAR(Date_of_Birth__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Age</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/APEX_Candidate__c/fields/APEX_Country__c.field-meta.xml
<CustomField>
    <fullName>APEX_Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>United States</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/APEX_Candidate__c/fields/Date_of_Birth__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Birth__c</fullName>
    <description>Date of Birth Field</description>
    <label>Date of Birth</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/APEX_Candidate__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>This is Email field</description>
    <inlineHelpText>Insert valid email only</inlineHelpText>
    <label>Email</label>
    <required>true</required>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/APEX_Candidate__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <description>This is first name field</description>
    <inlineHelpText>enter up to 15 char only</inlineHelpText>
    <label>First Name</label>
    <length>15</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/APEX_Candidate__c/fields/Jobs__c.field-meta.xml
<CustomField>
    <fullName>Jobs__c</fullName>
    <description>It should be able to relate a candidate to a job</description>
    <label>Job</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Candidates</relationshipLabel>
    <relationshipName>Candidates</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/APEX_Candidate__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <description>last name field</description>
    <inlineHelpText>enter last name max 15 char</inlineHelpText>
    <label>Last Name</label>
    <length>15</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/getAllCandidates.cls
public class getAllCandidates {
    
    public ApexPages.StandardSetController setCon {
        get {
            if(setCon == null) {
                setCon = new ApexPages.StandardSetController(Database.getQueryLocator(
                    [
                     SELECT First_Name__c, Last_Name__c,Age__c,Email__c,
                     Date_of_Birth__c,Jobs__c,
                     APEX_Country__c FROM APEX_Candidate__c
                     
                    ]
                ));
            }
            return setCon;
        }
        set;
    }
    // Initialize setCon and return a list of records
    public List<APEX_Candidate__c> getOpportunities() {
        return (List<APEX_Candidate__c>) setCon.getRecords();
    }


}