force-app/main/default/objects/APEX_Candidate__c/APEX_Candidate__c.object-meta.xml
<CustomObject>
    <description>This object contain candidate detail</description>
    <label>Candidate</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Candidate Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/APEX_Candidate__c/fields/Application_Date__c.field-meta.xml
<CustomField>
    <fullName>Application_Date__c</fullName>
    <description>application submission date</description>
    <inlineHelpText>select date</inlineHelpText>
    <label>Application Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/APEX_Candidate__c/fields/Jobs__c.field-meta.xml
<CustomField>
    <fullName>Jobs__c</fullName>
    <description>It should be able to relate a candidate to a job</description>
    <label>Job</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Candidates</relationshipLabel>
    <relationshipName>Candidates</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <description>This is a job object</description>
    <label>Job</label>
    <nameField>
        <displayFormat>J-{0000}</displayFormat>
        <label>Job Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/CandidateTriggerHandlerClass.cls
public class CandidateTriggerHandlerClass {
    //
    //   Task 1 B Start Here
    //
    //
    public static void checkJobStatus(List<APEX_Candidate__c> listCandidate)
    {
        Set<Id> jobId = new Set<Id>();
        
        for(APEX_Candidate__c objcandidate : listCandidate)
        {
            if(objcandidate.Jobs__c!=null)
            {
                jobId.add(objcandidate.Jobs__c);
            }
        }
        Map<Id,Job__c>  deactivateJob = new Map<Id,Job__c>([SELECT Id,Active__c from Job__c where Id In:
                                                           jobid AND Active__c=false]);
        
        for(APEX_Candidate__c objCandidate:listCandidate)
        {
            if(deactivateJob.get(objCandidate.Jobs__c)!=null){
                objCandidate.addError('This job is not active. You can not apply for this job');
            }   
        }
    }
    
    //   Task 1 B Ends Here
    
    
    
    //  task 2  start here
    public static void addDate(List<APEX_Candidate__c> newCandidate)
    {
        List<APEX_Candidate__c> listOfCandidate = new List<APEX_Candidate__c>();
        
        
        for(APEX_Candidate__c obj : newCandidate)
        {
            APEX_Candidate__c newObj = new APEX_Candidate__c();
            
            
            newObj.Id =  obj.Id;
            newObj.Application_Date__c=  obj.CreatedDate.date();
            listOfCandidate.add(newObj);
            
            
            
        }
        Update listOfCandidate;
        //System.debug('List of Candidate after update ' +listOfCandidate );
        //System.debug('New object ' +newObj );
            //System.debug('New object after add ' +newObj );
           //System.debug('List of Candidate ' +listOfCandidate );
            //System.debug('Get hello from get date function' + obj.CreatedDate.date());
        
        
        
    }
    //  task 2 ends here

}