force-app/main/default/objects/APEX_Candidate__c/APEX_Candidate__c.object-meta.xml
<CustomObject>
    <description>This object contain candidate detail</description>
    <label>Candidate</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Candidate Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/APEX_Candidate__c/fields/Application_Date__c.field-meta.xml
<CustomField>
    <fullName>Application_Date__c</fullName>
    <description>application submission date</description>
    <inlineHelpText>select date</inlineHelpText>
    <label>Application Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/APEX_Candidate__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>This is Email field</description>
    <inlineHelpText>Insert valid email only</inlineHelpText>
    <label>Email</label>
    <required>true</required>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/APEX_Candidate__c/fields/Expected_Salary__c.field-meta.xml
<CustomField>
    <fullName>Expected_Salary__c</fullName>
    <label>Expected Salary</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/APEX_Candidate__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <description>This is first name field</description>
    <inlineHelpText>enter up to 15 char only</inlineHelpText>
    <label>First Name</label>
    <length>15</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/APEX_Candidate__c/fields/Jobs__c.field-meta.xml
<CustomField>
    <fullName>Jobs__c</fullName>
    <description>It should be able to relate a candidate to a job</description>
    <label>Job</label>
    <referenceTo>Job__c</referenceTo>
    <relationshipLabel>Candidates</relationshipLabel>
    <relationshipName>Candidates</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/APEX_Candidate__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <description>last name field</description>
    <inlineHelpText>enter last name max 15 char</inlineHelpText>
    <label>Last Name</label>
    <length>15</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <description>This is a job object</description>
    <label>Job</label>
    <nameField>
        <displayFormat>J-{0000}</displayFormat>
        <label>Job Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job__c/fields/Job_Types__c.field-meta.xml
<CustomField>
    <fullName>Job_Types__c</fullName>
    <description>These are available jobs types</description>
    <label>Job Types</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Manager</fullName>
            </value>
            <value>
                <fullName>Developer</fullName>
            </value>
            <value>
                <fullName>Admin</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job__c/fields/Manager__c.field-meta.xml
<CustomField>
    <fullName>Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field indicates the relation of job record to the Contact record.</description>
    <label>Manager</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job__c/fields/Number_of_Positions__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Positions__c</fullName>
    <description>Number of Positions  filed</description>
    <inlineHelpText>you can add up to 10 digits</inlineHelpText>
    <label>Number of Positions</label>
    <precision>10</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CandidateTriggerTestClass.cls
@isTest
private class CandidateTriggerTestClass {
    
    @testSetup
    public static void createRecord()
    {
        Contact contact = new Contact(LastName ='Sharma');
       	insert contact;
        
        List<Job__c> jobList = new List<Job__c>();
        jobList.add(new Job__c(Job_Types__c='Manager',Active__c=false,Number_of_Positions__c =10,Manager__c = contact.id));
        jobList.add(new Job__c(Job_Types__c='Manager',Active__c=false,Number_of_Positions__c =10,Manager__c = contact.id));
        
        Database.insert(jobList);
        
        List<APEX_Candidate__c> candidateList = new List<APEX_Candidate__c>();
        candidateList.add(new APEX_Candidate__c(Application_Date__c=Date.today().addDays(8),First_Name__c='radhe',Last_Name__c='bhaiya',Expected_Salary__c=1000,Email__c= 'Radhe@gmail.com',Status__c='Reject',Jobs__c=jobList[0].id));
                                                              
    }
    
   
    
   @isTest
    public static void dateCheck()
    {
        List<APEX_Candidate__c> lstCandidate =[SELECT Application_Date__c FROM APEX_Candidate__c];
            for(APEX_Candidate__c objCandidate : lstCandidate)
        	{
            	System.assertEquals(Date.today(), objCandidate.Application_Date__c);
               
                
			}
        
    } 
    
     @isTest
    public static void checkStatus()
    {
         List<Job__c> listOfJob =[SELECT Active__c,Id FROM Job__c];
        
        for(Job__c jobList: listOfJob)
        {
           
            Database.deleteResult result = Database.delete(jobList.Id);
            System.assertEquals(false,!result.isSuccess());
        }
    }
    
    @isTest 
    public static void salaryValidation() {
        // Test data setup
        // Create an account with an opportunity, and then try to delete it
        List<Job__c> jobList = [SELECT Id from  Job__c];
        
         List<APEX_Candidate__c> candidateList = new List<APEX_Candidate__c>();
        
		 candidateList.add(new APEX_Candidate__c(First_Name__c='radhe',Last_Name__c='bhaiya',Expected_Salary__c=1000,Email__c= 'Radhe@gmail.com',Status__c='Reject',Jobs__c=jobList[0].Id));  
        candidateList.add(new APEX_Candidate__c(First_Name__c='radhe',Last_Name__c='bhaiya',Expected_Salary__c=null,Email__c= 'Radhe@gmail.com',Status__c='Reject',Jobs__c=jobList[0].Id));  
      
      	 Database.SaveResult[] result = Database.insert(candidateList,false);
        System.assertEquals(false,result[1].isSuccess());
        
      
    }
    /*
      
       @isTest
    public static void checkStatus()
    {
         List<Job__c> listOfJob =[SELECT Active__c FROM Job__c];
        
        for(Job__c jobList: listOfJob)
        {
           
            System.assertEquals(false,jobList.Active__c);
        }
    }
      
      
     @isTest 
    public static void deleteJobCheck() {
        // Test data setup
        // Create an account with an opportunity, and then try to delete it
        List<Job__c> jobList = [SELECT Id from  Job__c];
        
         List<APEX_Candidate__c> candidateList = new List<APEX_Candidate__c>();
        
		 candidateList.add(new APEX_Candidate__c(First_Name__c='radhe',Last_Name__c='bhaiya',Expected_Salary__c=1000,Email__c= 'Radhe@gmail.com',Status__c='Reject',Jobs__c=jobList[0].Id));  
         candidateList.add(new APEX_Candidate__c(First_Name__c='radhe',Last_Name__c='bhaiya',Expected_Salary__c=100,Email__c= 'Radhe@gmail.com',Status__c='Reject',Jobs__c=jobList[0].Id));  
      
      	 Database.DeleteResult[] result = Database.delete(jobList,true);
         System.assertEquals(false,!result[0].isSuccess());
        
        
      
    }
*/
    
}