force-app/main/default/objects/APEX_Candidate__c/APEX_Candidate__c.object-meta.xml
<CustomObject>
    <description>This object contain candidate detail</description>
    <label>Candidate</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Candidate Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/APEX_Candidate__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>This is Email field</description>
    <inlineHelpText>Insert valid email only</inlineHelpText>
    <label>Email</label>
    <required>true</required>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/APEX_Candidate__c/fields/Expected_Salary__c.field-meta.xml
<CustomField>
    <fullName>Expected_Salary__c</fullName>
    <label>Expected Salary</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/APEX_Candidate__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <description>This is first name field</description>
    <inlineHelpText>enter up to 15 char only</inlineHelpText>
    <label>First Name</label>
    <length>15</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/APEX_Candidate__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <description>last name field</description>
    <inlineHelpText>enter last name max 15 char</inlineHelpText>
    <label>Last Name</label>
    <length>15</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <description>This is a job object</description>
    <label>Job</label>
    <nameField>
        <displayFormat>J-{0000}</displayFormat>
        <label>Job Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <description>This is auto field</description>
    <displayFormat>JOB-{000}</displayFormat>
    <label>Name</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/classes/TestMethod1Candidate.cls
@isTest
public class TestMethod1Candidate {
    
    static testMethod void expextedSalaryTest()
    {
        APEX_Candidate__c candidateObj=new APEX_Candidate__c();
        candidateObj.First_Name__c= 'savita';
		candidateObj.Last_Name__c= 'Borse';
		candidateObj.Email__c= 'janvi@gmail.com';
		candidateObj.Status__c= 'Applied';
        candidateObj.Expected_Salary__c=199;
       
        insert candidateObj;
        
        Test.startTest();
        candidateObj.Expected_Salary__c=66;
       
        update candidateObj;
        Test.stopTest();
        
       List <Job__c> jobList = [select Id, Name__c from Job__c where Id =:candidateObj.id];
      // List< Candidate_Shweta_c> canList = [SELECT Id, APEX_ExpectedSalaryc FROM Candidate_Shwetac WHERE APEX_FirstName_c  = :candidateObj.id];
       //List<Candidate_Shweta_c> candidateList = [SELECT Id, Candidate_Shwetac FROM Candidate_Shwetac WHERE  Candidate_Shweta_c= :candidateObj.id];
        system.assertEquals(1, jobList.size());
        
     }

}