force-app/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <description>This is a job object</description>
    <label>Job</label>
    <nameField>
        <displayFormat>J-{0000}</displayFormat>
        <label>Job Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job__c/fields/Hired_Applicants__c.field-meta.xml
<CustomField>
    <fullName>Hired_Applicants__c</fullName>
    <description>This field indicates the count of the total Hired candidate has applied to this job.

It should be a numeric field and must be calculated automatically as any candidate is hired for a job( Candidate status = ‘Hired’);</description>
    <label>Hired Applicants</label>
    <summaryForeignKey>APEX_Candidate__c.Jobs__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Job__c/fields/Manager__c.field-meta.xml
<CustomField>
    <fullName>Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field indicates the relation of job record to the Contact record.</description>
    <label>Manager</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job__c/fields/Number_of_Positions__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Positions__c</fullName>
    <description>Number of Positions  filed</description>
    <inlineHelpText>you can add up to 10 digits</inlineHelpText>
    <label>Number of Positions</label>
    <precision>10</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/JobTriggerHandlerClass.cls
public class JobTriggerHandlerClass {
    // Task 4 start here
    public static void deactivateJob(List<Job__c> listJob)
    {
        for(Job__c objjob:listJob)
        {
            if(objjob.Number_of_Positions__c==objjob.Hired_Applicants__c)
            {
                objjob.Active__c=false;
            }
        }
    }
    // Task 4 ends here
    
    
    // Task 6 start here
    public static void updateActiveField(List<Job__c> listJob)
    {
        for(Job__c obj:listJob)
        {
            if(obj.Active__c==false && obj.Number_of_Positions__c >obj.Hired_Applicants__c )
            {
                obj.Active__c=true;
            }
        }
    }
    // Task 6 ends here
    
    
    // Task 5 start here
    
        public static void sendMail(List<Job__c> Job_lst) 
        {
        //List<Messaging.SingleEmailMessage> mails = new List<Messaging.SingleEmailMessage>();
        List<Messaging.Email> mails = new List<Messaging.Email>();
        Messaging.SingleEmailMessage mail =  new Messaging.SingleEmailMessage();
        List<String> sendTo = new List<String>();
        for(Job__c job_obj:Job_lst) {
            if(job_obj.Number_of_Positions__c==job_obj.Hired_Applicants__c)
            {
                sendTo.add(job_obj.Manager__c);
                mail.setToAddresses(sendTo);
                mail.setSubject('Vacancy full');
                String body = 'All required candidate has been hired for this job on' +job_obj.LastModifiedDate ;
                mail.setHtmlBody(body);
                mails.add(mail);
            }
           
        }
        Messaging.sendEmail(mails);
    
    }
    //send email ends here
    

}